name: Continuous Integration

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

jobs:
  nestor_typescript_ci:
    name: Typescript
    uses: youwol-jdecharne/nestor/.github/workflows/typescript-ci.yml@v3
    with:
      pyYouwolRef: feature/refactor
